# Site settings
title: The Free Font Movement
description: > # this means to ignore newlines until "baseurl:"
  Dave Crossland's MATD Dissertation
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
